base_images:
  base:
    name: "4.12"
    namespace: ocp
    tag: base
binary_build_commands: build binaries
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.17
promotion:
  name: "4.12"
  namespace: ocp
releases:
  initial:
    integration:
      name: "4.12"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.12"
      namespace: ocp
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: unit
  commands: make teest-unit
  container:
    from: src
- as: e2e
  steps:
    cluster_profile: aws
    test:
    - as: e2e
      cli: latest
      commands: make test-e2e
      from: src
      resources:
        requests:
          cpu: 100m
    workflow: ipi-aws
zz_generated_metadata:
  branch: master
  org: openshift
  repo: sandboxed-containers-operator
