approve:
- commandHelpLink: ""
  repos:
  - openshift/sandboxed-containers-operator
  require_self_approval: false
lgtm:
- repos:
  - openshift/sandboxed-containers-operator
  review_acts_as_lgtm: true
plugins:
  openshift/sandboxed-containers-operator:
    plugins:
    - approve
